version: '3.4'

services:
    mongodb:
      image: mongo:8
      deploy:
        placement:
          constraints:
            - node.role == manager
      environment:
        MONGO_INITDB_ROOT_USERNAME: mongoadmin
        MONGO_INITDB_ROOT_PASSWORD: Tourch@in#179
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
      networks:
        - default 

networks:
  default:

volumes:
  letsencrypt:
  mongodb_data:
    external: true